version: '3.8'
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfiles/postgres/Dockerfile
    container_name: postgres
    shm_size: 1024mb
    expose:
      - 5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: charging
    networks:
      - ChargingNetwork
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfiles/backend/Dockerfile
    environment:
      - DEBUG=True
      - SECRET_KEY=test
      - ALLOWED_HOSTS=*
    deploy:
      replicas: 3
    volumes:
      - ./:/app
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - postgres
    networks:
      - ChargingNetwork
    restart: always
  nginx:
    build:
      context: .
      dockerfile: Dockerfiles/nginx/Dockerfile
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./Dockerfiles/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/home/app/static
      - media_volume:/home/app/media
    depends_on:
      - backend
    networks:
      - ChargingNetwork
  locust:
    build:
      context: .
      dockerfile: Dockerfiles/locust/Dockerfile  
    container_name: locust
    volumes:
      - ./core/locust:/mnt/locust
    ports:
      - "4545:8089"  
    networks:
      - ChargingNetwork
    command: -f /mnt/locust/locustfile.py --host=http://nginx

networks:
  ChargingNetwork:
    name: ChargingNetwork

volumes:
  static_volume:
  media_volume:
